[package]
name = "boolog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
homedir = "0.3.4"
rstring-builder = "0.1.4"
serde_json = "1.0.140"
uuid = {  version = "1.16.0", features = ["serde", "v4"] }
serde = { version = "1.0.219", features = ["derive"] }
reqwest = "0.12.15"
